-- Slice 2a (post-v1) — MCP server / agent actions log
--
-- Adds `agent_actions` to log every WRITE performed by an MCP-driven agent
-- session. Reads are intentionally not logged (signal/bruit ratio + no audit
-- value). Intents (LLM calls triggered by the agent) are logged here AND in
-- `runs` (existing).
--
-- `agent_session_id` is an opaque string generated by the MCP server at
-- session start (ULID/uuid) — lets the UI group "what this agent did in this
-- session". `payload` carries human-readable context to render a row without
-- requiring a join (e.g. note title at write time, link from→to, etc.).
--
-- RLS: owner-scoped. The MCP server uses the Supabase service role key, so
-- RLS is bypassed at runtime, but the policy is still defined to keep the
-- table consistent with the rest of the schema (the /agent-activity UI in the
-- app uses the user-scoped anon key and DOES need the policy).
--
-- Migration is idempotent: safe to re-apply.

-- ─── agent_actions table ──────────────────────────────────────────────────

create table if not exists public.agent_actions (
  id uuid primary key default gen_random_uuid(),
  world_id uuid not null references public.worlds(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  agent_session_id text not null,
  action_kind text not null,
  target_kind text,
  target_id uuid,
  payload jsonb,
  created_at timestamptz not null default now()
);

create index if not exists agent_actions_world_created_idx
  on public.agent_actions (world_id, created_at desc);

create index if not exists agent_actions_session_idx
  on public.agent_actions (agent_session_id);

-- ─── RLS ──────────────────────────────────────────────────────────────────

alter table public.agent_actions enable row level security;

drop policy if exists agent_actions_owner on public.agent_actions;
create policy agent_actions_owner on public.agent_actions
  for all
  using (owner_id = auth.uid())
  with check (owner_id = auth.uid());
